#!/usr/bin/env python
"""Render `configs/testbed.yaml` into the formats each reader actually demands.

    ./.venv/bin/python scripts/apply_config.py          # write the generated files
    ./.venv/bin/python scripts/apply_config.py --check  # fail if they are stale

Two of the three config formats in this project are not ours. `settings.json` is AirSim's
schema, read by the CarlaUE4 binary at launch; the ROS parameter file is rclpy's schema, read
by the parameter system. Neither reader will accept a unified file, so the unification has to
happen one level up: one source, rendered into what each consumer insists on.

Generated files carry a DO-NOT-EDIT header, and `--check` regenerates into memory and diffs.
`tests/test_config.py` runs that check, so drift fails a test rather than a flight.

Runs under either interpreter — it imports only yaml, json and the standard library — because
`run_sim.sh` calls it from the 3.10 side and a ROS launch may want it from 3.12.
"""
from __future__ import annotations

import argparse
import json
import os
import sys

PROJ = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(PROJ, "configs", "testbed.yaml")
AIRSIM_OUT = os.path.join(PROJ, "configs", "sim", "settings.json")
# Rendered straight into the bringup package rather than a configs/generated/ of our own.
# The launch file's `params` argument DEFAULTS to this path, so anything else leaves a second
# parameter file that `ros2 launch bringup testbed.launch.py` silently prefers - which is the
# exact two-sources-of-truth failure C-01 existed to remove, and it survived C-01 unnoticed.
PARAMS_OUT = os.path.join(PROJ, "ros2_ws", "src", "bringup", "config", "testbed.yaml")

BANNER = ("GENERATED by scripts/apply_config.py from configs/testbed.yaml. "
          "Edit that file, not this one.")

#: AirSim's ImageType enum. Only the three the testbed uses; the rest are available at
#: capture time without being configured here.
IMAGE_TYPE = {"rgb": 0, "depth": 2, "segmentation": 5}


def load(path=SOURCE):
    import yaml
    with open(path) as fh:
        return yaml.safe_load(fh)


class ConfigError(Exception):
    """A config that would produce a working simulator measuring the wrong thing."""


def validate(cfg):
    """Reject a config whose camera buffers disagree, BEFORE the simulator starts.

    `fov` is HORIZONTAL. Two buffers with the same `fov` and different aspect ratios cover
    different VERTICAL fields, so `scale_to()` maps an RGB pixel onto the wrong depth pixel —
    silently, on every waypoint, in a simulator that starts cleanly and looks correct.

    This is the same shape as the bug that had `docs/ros2-api.html` publishing intrinsics for
    a 640x480 buffer while the config said 960x720: nothing errors, the numbers are simply
    wrong. A config error that only a test catches is one that reaches a flight whenever the
    test is not run, so it is raised here, at render time, where every launch goes through.

    Returns a list of human-readable problems; empty means the config is usable.
    """
    problems = []
    cams = ((cfg.get("simulator") or {}).get("cameras") or {})
    if not cams:
        return ["simulator.cameras is empty — no camera would be configured at all"]

    ratios = {}
    for name, c in cams.items():
        try:
            w, h, fov = int(c["width"]), int(c["height"]), float(c["fov"])
        except (KeyError, TypeError, ValueError):
            problems.append(f"simulator.cameras.{name}: needs integer width and height "
                            f"and a numeric fov")
            continue
        if w <= 0 or h <= 0:
            problems.append(f"simulator.cameras.{name}: width and height must be positive, "
                            f"got {w}x{h}")
            continue
        if not 1.0 < fov < 180.0:
            problems.append(f"simulator.cameras.{name}: fov must be between 1 and 180 "
                            f"degrees, got {fov}")
        ratios[name] = (w / h, w, h)

    distinct = {round(r, 6) for r, _, _ in ratios.values()}
    if len(distinct) > 1:
        shown = ", ".join(f"{n} {w}x{h} ({r:.3f})" for n, (r, w, h) in sorted(ratios.items()))
        problems.append(
            "camera buffers must all share one aspect ratio, because `fov` is HORIZONTAL:\n"
            f"           {shown}\n"
            "         Equal fov at different aspects covers a different VERTICAL field, so a\n"
            "         pixel index from the RGB frame reads the wrong place in depth — with no\n"
            "         error, on every waypoint. Pick one ratio; 4:3 is what ships\n"
            "         (960x720 rgb, 160x120 depth, 320x240 segmentation).")
    return problems


def render_airsim(cfg):
    """The AirSim settings the simulator reads at launch.

    Only `simulator:` reaches here. The CARLA sensors do not: they are actors our sidecar
    spawns after the simulator is already up, and AirSim has never heard of them.
    """
    sim = cfg["simulator"]
    capture = [
        {"ImageType": IMAGE_TYPE[name], "Width": int(c["width"]),
         "Height": int(c["height"]), "FOV_Degrees": int(c["fov"])}
        for name, c in sim["cameras"].items() if name in IMAGE_TYPE
    ]
    out = {
        "_comment": BANNER,
        "SettingsVersion": 1.2,
        "SimMode": "Multirotor",
        "ClockSpeed": float(sim.get("clock_speed", 1.0)),
        "Vehicles": {
            "SimpleFlight": {
                "VehicleType": "SimpleFlight",
                "AutoCreate": True,
                "Cameras": {"0": {
                    "CaptureSettings": capture,
                    "X": 0.5, "Y": 0.0, "Z": 0.1,
                    "Pitch": 0.0, "Roll": 0.0, "Yaw": 0.0,
                }},
            }
        },
    }
    origin = sim.get("gps_origin") or {}
    # Omitted entirely when unset, rather than written as zeros: AirSim treats a present
    # OriginGeopoint as authoritative, so {0, 0} would silently move the aircraft to the
    # Atlantic instead of falling back to the default.
    if origin.get("lat") is not None and origin.get("lon") is not None:
        out["OriginGeopoint"] = {"Latitude": float(origin["lat"]),
                                 "Longitude": float(origin["lon"]),
                                 "Altitude": float(origin.get("alt") or 0.0)}
    return json.dumps(out, indent=4) + "\n"


def render_params(cfg):
    """The ROS 2 parameter file, in rclpy's `node: ros__parameters:` schema."""
    import yaml
    graph = dict(cfg["graph"])
    graph.pop("ros_domain_id", None)          # an environment variable, not a parameter
    doc = {node: {"ros__parameters": params} for node, params in graph.items()}
    text = yaml.safe_dump(doc, sort_keys=False, default_flow_style=False)
    return f"# {BANNER}\n" + text


def sensors_for(cfg, source):
    """The enabled sensors from one source, in the shape that consumer expects."""
    return [s for s in cfg.get("sensors", [])
            if s.get("enabled") and s.get("source") == source]


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    existing = None
    if os.path.exists(path):
        with open(path) as fh:
            existing = fh.read()
    if existing == text:
        return False
    with open(path, "w") as fh:
        fh.write(text)
    return True


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--source", default=SOURCE, metavar="PATH",
                    help="the config to render (default: configs/testbed.yaml)")
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if a generated file is out of date")
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args()

    if not os.path.exists(args.source):
        print(f"no such config: {args.source}", file=sys.stderr)
        return 2
    cfg = load(args.source)

    # Before anything is rendered. A bad config that reaches settings.json is a simulator
    # that starts, runs, and measures the wrong thing.
    problems = validate(cfg)
    if problems:
        print(f"ERROR: {args.source} is not usable:", file=sys.stderr)
        for problem in problems:
            print(f"  * {problem}", file=sys.stderr)
        return 2

    targets = [(AIRSIM_OUT, render_airsim(cfg)), (PARAMS_OUT, render_params(cfg))]

    if args.check:
        stale = []
        for path, text in targets:
            current = None
            if os.path.exists(path):
                with open(path) as fh:
                    current = fh.read()
            if current != text:
                stale.append(os.path.relpath(path, PROJ))
        if stale:
            print("STALE, run scripts/apply_config.py: " + ", ".join(stale), file=sys.stderr)
            return 1
        if not args.quiet:
            print("generated config is up to date")
        return 0

    changed = [os.path.relpath(p, PROJ) for p, t in targets if write(p, t)]
    if not args.quiet:
        air = sensors_for(cfg, "airsim")
        carla = sensors_for(cfg, "carla")
        print(f"config: {len(air)} airsim + {len(carla)} carla sensors enabled"
              f"  ({', '.join(s['name'] for s in air + carla)})")
        print("  " + ("wrote " + ", ".join(changed) if changed else "already up to date"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
